### ISSUE TITLE
Playing Z1 and Z2 Games?

### ISSUE THREAD

**Issue by jeffnyman** [mjdarby/Fic#1]
I wasn't sure if you wanted to support v1 and v2, rare as they are. I realize the goal as stated was v3. Just wasn't sure if that was due to lack of having access to z1 and z2 files.

Currently running such will get you the following error:

    in getEncodedAbbreviationString
    abbrev_addr = self.getWord(abbrev_addr)*2
    RecursionError: maximum recursion depth exceeded

If it helps and you want to support the previous versions, you can use the following story files (from my zifmia repository) for testing purposes: https://github.com/jeffnyman/zifmia/tree/master/zorks, where I have z1 and z2 versions that I created from patches.

**Comment by mjdarby** [comment]
Hi, thanks for bringing this up - I didn't have a z1 or z2 to play with before! I went ahead and just pushed a commit to support z1/z2 text. Looking through the spec there's not much else different between z1/z2/z3, but I'm sure something else will come up. The test suite is super useful by the way, I'll be making more use of it later!
